---
# tasks file for sa-chatops-errbot

  - include_tasks: sa-python/main.yml
    when: option_install_python

  - include_tasks: sa-python3/main.yml
    when: option_install_python   

  - include_tasks: sa-supervisord/main.yml
    when: option_install_supervisor

  - include_tasks: tasks_errbot.yml 
